// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbhlszbljsljvsnigdtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5iaGxzemJsanNsanZzbmlnZHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTY3ODIsImV4cCI6MjA2NDM3Mjc4Mn0.8RoSA8u0X9ftNPVwa-SiXugxxqRnJjjQ6aBvAZOQnRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);